# Database Configuration
spring.datasource.url=jdbc:oracle:thin:@rds.czisqegmscrt.ap-south-1.rds.amazonaws.com:1521/ORCL
spring.datasource.username=admin
spring.datasource.password=LA2025fmr
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Spring Data JDBC Configuration
spring.sql.init.mode=never
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Spring Data JDBC specific configuration
spring.data.jdbc.repositories.enabled=true
spring.data.jdbc.schema=classpath:schema.sql

# Logging for debugging
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.data.jdbc=DEBUG
logging.level.org.springframework.data.jdbc.core=DEBUG

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mappers/*.xml

fmts.url=http://fmts-nodejs:3000/fmts/client
fmts.trade.url=http://fmts-nodejs:3000/fmts/trades/trade
